//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationSlot
    {
        public int ID { get; set; }
        public int ParkingPlaceID { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ReservationID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual ParkingPlace ParkingPlace { get; set; }
    }
}
